import { ProjectItem } from "../types/projects";

export const PROJECTS: ProjectItem[] = [{
  id: 1,
  title: "Website Cinema",
  slug: "web-cineme",
  description: "A movie ticket website for room reservations online",
  image: "/images/projects/cinema.png",
  link_demo: "https://zuhot.id.vn/",
  link_github: "https://github.com/anbvt/web-cinema",
  stacks: ["Next.js", "SpringBoot", "PostgreSql", "AWS"],
  content: "This project highlights my team and experiences with SpringBoot and NextJS.",
  is_show: true,
  is_featured: true,
},
{
  id: 2,
  title: "Website Laptop",
  slug: "web-laptop",
  description: "A laptop website for product reservations online",
  image: "/images/projects/laptop.png",
  link_demo: "https://zuhot-laptop.vercel.app/",
  link_github: "https://github.com/anbvt/web-laptop",
  stacks: ["React.js", "SpringBoot", "PostgreSql", "Supabase"],
  content: "A complete e-commerce platform with authentication, product management, and payment integration.",
  is_show: true,
  is_featured: true,
},
{
  id: 3,
  title: "My Portfolio-v2",
  slug: "my-portfolio",
  description: "A website for me",
  image: "/images/projects/portfolio-v2.png",
  link_demo: "https://buivuthienan.id.vn/",
  link_github: "https://github.com/anbvt/portfolio-v2",
  stacks: ["React.js"],
  content: "A complete e-commerce platform with authentication, product management, and payment integration.",
  is_show: true,
  is_featured: false
},
{
  id: 4,
  title: "My Portfolio-v1",
  slug: "my-portfolio-v1",
  description: "A website for me",
  image: "/images/projects/portfolio-v1.png",
  link_demo: "https://anbvt-portfolio.vercel.app/",
  link_github: "https://github.com/anbvt/portfolio",
  stacks: ["React.js"],
  content: "A complete e-commerce platform with authentication, product management, and payment integration.",
  is_show: true,
  is_featured: false
},
{
  id: 5,
  title: "Glasses Shop",
  slug: "glasses-shop",
  description: "A glasses website for product reservations online",
  image: "/images/projects/glasses.png",
  link_demo: "https://anbvt-portfolio.vercel.app/",
  link_github: "https://github.com/anbvt/glasses-stores",
  stacks: ["SpringBoot", "PostgreSql"],
  content: "A complete e-commerce platform with authentication, product management, and payment integration.",
  is_show: true,
  is_featured: false
},
]